#服务配置
Server:
  Name: gin_web
  RunMode: dev  #控制日志输出位置
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
#  应用配置
App:
#  Model: dev
  Level: debug  #日志输出级别
  LogSavePath: storage/logs
  LogFileName: gin_web
  LogFileExt: .log
  LocalTime: true  #格式化时间
  Compress: false  #压缩，默认不压缩
  MaxSize: 1  #单位是 MB
  MaxBackups: 2
  MaxAge: 1
#数据库配置
Database:
  mysql:
    DBType: mysql
    UserName: root
    Password: ydw@123
    Host: 127.0.0.1
    Port: 3306
    DBName: gin_web_service
    TablePrefix: blog_
    Charset: utf8
    ParseTime: True
    MaxIdleConns: 10
    MaxOpenConns: 30
  redis:
    Host: 127.0.0.1
    Port: 6379