#服务配置
Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
#  应用配置
App:
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
#数据库配置
Database:
  mysql:
    UserName: root
    Password: ydw@123
    Host: 127.0.0.1
    Port: 3306
    DBName: gin_web_service
    TablePrefix: blog_
    Charset: utf8
    ParseTime: True
    MaxIdleConns: 10
    MaxOpenConns: 30