#服务配置
Server:
  Name: gin_web
  RunMode: debug  #控制日志输出位置和 gin 运行级别  设置 debug,test,release
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
  MachineId : 1  #雪花算法机器数量，还没搞太明白
#  应用配置
App:
#  Model: dev
  Level: debug  #日志输出级别
  LogSavePath: storage/logs
  LogFileName: gin_web
  LogFileExt: .log
  LocalTime: true  #格式化时间
  Compress: false  #压缩，默认不压缩
  MaxSize: 1  #日志大小单位是 MB
  MaxBackups: 2  #日志份副本书
  MaxAge: 1  #最大天数
  DefaultPageSize: 20   #默认一页数据数量
  MaxPageSize: 100  #每页可显示的最大数据数量
#数据库配置
Database:
  mysql:
    DBType: mysql
    UserName: root
    Password: ydw@123
    Host: 127.0.0.1
    Port: 3306
    DBName: gin_web_service
    TablePrefix: web_
    Charset: utf8
    ParseTime: True
    MaxIdleConns: 10
    MaxOpenConns: 30
  redis:
    Host: 127.0.0.1
    Port: 6379