#服务配置
Server:
  Name: gin_web
  RunMode: debug  #控制日志输出位置和 gin 运行级别  设置 debug,test,release
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
  MachineId: 1  #雪花算法机器数量，还没搞太明白
  StartTime: "2023-1-19"   #这里要写成字符串，不然解析为时间类型了
#  应用配置
App:
  #这个有时间再看看，目前不生效好像
  ContextTimeout:
    ContextTimeout: 1 #这里单位也是秒
  Log:
    #  Model: dev
    Level: debug  #日志输出级别
    LogSavePath: storage/logs
    LogFileName: gin_web
    LogFileExt: .log
    LocalTime: true  #格式化时间
    Compress: false  #压缩，默认不压缩
    MaxSize: 1  #日志大小单位是 MB
    MaxBackups: 2  #日志份副本书
    MaxAge: 1  #最大天数
  Page:
    DefaultPageSize: 20   #默认一页数据数量
    MaxPageSize: 100  #每页可显示的最大数据数量
  UploadImage:
    UploadSavePath: storage/uploads
    UploadServerUrl: http://127.0.0.1:8080/api/v1/static
    UploadImageMaxSize: 5  # MB
    UploadImageAllowExts:
      - .jpg
      - .jpeg
      - .png
    #认证
  JWT:
    Secret: aloys
    Issuer: web_service
    Expire: 7200000000   #这是秒，aToken 有效期
  #邮件配置
  Email:
    Host: smtp.qq.com
    Port: 465
    UserName: XXXXXX
    Password: XXXXXX
    IsSSL: true
    From: XXXXXX
    To:
      - XXXXXX
  #令牌桶
  Limiter:
    Auth:
      Key: /auth        # 限流的接口
      FillInterval: 10       # 添加的时间间隔，单位秒
      Capacity: 10           #令牌桶容量
      Quantum: 10           #每次添加令牌
#数据库配置
Database:
  Mysql:
    DBType: mysql
    UserName: root
    Password: ydw@123
    Host: 127.0.0.1
    Port: 3306
    DBName: gin_web_service
    TablePrefix: web_
    Charset: utf8
    ParseTime: True
    MaxIdleConns: 10
    MaxOpenConns: 30
  Redis:
    Host: 127.0.0.1
    Port: 6379