definitions:
  app.Pager:
    properties:
      page:
        description: 页码
        type: integer
      page_size:
        description: 每页数量
        type: integer
      total_rows:
        description: 总行数
        type: integer
    type: object
  errcode.Error:
    type: object
  model.Tag:
    properties:
      created_by:
        description: 创建人
        type: integer
      created_on:
        description: 创建时间 ，自动获取提交时间
        type: integer
      deleted_on:
        description: 删除时间，自动获取提交时间
        type: integer
      is_del:
        description: 是否删除 0 正常,1为删除，默认初始化 0
        type: integer
      modified_by:
        description: 修改人
        type: integer
      modified_on:
        description: 修改时间，自动获取提交时间
        type: integer
      name:
        description: 名称
        type: string
      state:
        description: 状态  1 正常 0为禁用
        type: integer
      tag_id:
        description: 设置 tagID  string解决json解析的时候使用这个类型，解决前端传入和传入前端失真
        example: "0"
        type: string
    type: object
  params.AuthRequest:
    properties:
      app_key:
        maxLength: 20
        minLength: 5
        type: string
      app_secret:
        maxLength: 20
        minLength: 5
        type: string
    required:
    - app_key
    - app_secret
    type: object
  params.CreateTagRequest:
    properties:
      name:
        description: 名称；min 和 max 限制的是长度 2-100
        maxLength: 100
        minLength: 2
        type: string
    required:
    - name
    type: object
  params.UpdateTagRequest:
    properties:
      name:
        description: 名称;要修改的标签名称
        maxLength: 100
        type: string
      state:
        description: 状态；可以更新状态为不可用，需要传入
        enum:
        - 0
        - 1
        example: 1
        type: integer
    type: object
  third_party.Swagger:
    type: object
  third_party.SwaggerAuth:
    type: object
  third_party.SwaggerTage:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      page:
        $ref: '#/definitions/app.Pager'
    type: object
info:
  contact: {}
  description: 练习 Gin 写 web 服务
  termsOfService: https://github.com/aloysZY/gin_web
  title: gin_web
  version: "1.0"
paths:
  /api/v1/tags:
    get:
      description: 查询标签
      parameters:
      - description: 标签名称
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/third_party.SwaggerTage'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      security:
      - ApiKeyAuth: []
      summary: 查询标签
      tags:
      - 标签
    post:
      description: 添加标签接口
      parameters:
      - description: 创建标签
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/params.CreateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/third_party.Swagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      security:
      - ApiKeyAuth: []
      summary: 添加标签
      tags:
      - 标签
  /api/v1/tags/{id}:
    delete:
      description: 删除标签
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/third_party.Swagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      security:
      - ApiKeyAuth: []
      summary: 删除标签
      tags:
      - 标签
    put:
      description: 更新标签接口
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新标签
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/params.UpdateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/third_party.Swagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      security:
      - ApiKeyAuth: []
      summary: 更新标签
      tags:
      - 标签
  /auth:
    post:
      description: 登录接口
      parameters:
      - description: 用户登录
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/params.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/third_party.SwaggerAuth'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 登录
      tags:
      - 用户
  /signup:
    post:
      description: 注册接口
      parameters:
      - description: 注册用户
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/params.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/third_party.Swagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 注册
      tags:
      - 用户
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
