definitions:
  app.Pager:
    properties:
      page:
        description: 页码
        type: integer
      page_size:
        description: 每页数量
        type: integer
      total_rows:
        description: 总行数
        type: integer
    type: object
  app.Swagger:
    type: object
  app.SwaggerTage:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      page:
        $ref: '#/definitions/app.Pager'
    type: object
  errcode.Error:
    type: object
  model.Tag:
    properties:
      created_by:
        description: 创建人
        type: string
      created_on:
        description: 创建时间 ，自动获取提交时间
        type: integer
      deleted_on:
        description: 删除时间，自动获取提交时间
        type: integer
      is_del:
        description: 是否删除 0 正常,1为删除，默认初始化 0
        type: integer
      modified_by:
        description: 修改人
        type: string
      modified_on:
        description: 修改时间，自动获取提交时间
        type: integer
      name:
        description: 名称
        type: string
      state:
        description: 状态  1 正常 0为禁用
        type: integer
      tag_id:
        description: 设置 tagID  string解决json解析的时候使用这个类型，解决前端传入和传入前端失真
        example: "0"
        type: string
    type: object
  params.CreateTagRequest:
    properties:
      created_by:
        description: 创建人；以后从 token 中获取；min 和 max 限制的是长度 2-100s
        maxLength: 100
        minLength: 2
        type: string
      name:
        description: 名称；min 和 max 限制的是长度 2-100
        maxLength: 100
        minLength: 2
        type: string
      state:
        description: 创建状态；默认是 1 正常 0为禁用、1为启用
        enum:
        - 0
        - 1
        example: 1
        type: integer
    required:
    - created_by
    - name
    type: object
  params.UpdateTagRequest:
    properties:
      modified_by:
        description: 修改人;以后从token中获取
        maxLength: 100
        minLength: 2
        type: string
      name:
        description: 名称;要修改的标签名称
        maxLength: 100
        type: string
      state:
        description: 状态；可以更新状态为不可用
        enum:
        - 0
        - 1
        example: 1
        type: integer
    required:
    - modified_by
    type: object
info:
  contact: {}
  description: 练习 Gin 写 web 服务
  termsOfService: https://github.com/aloysZY/gin_web
  title: gin_web
  version: "1.0"
paths:
  /api/v1/tags:
    get:
      description: 获取多个标签
      parameters:
      - description: 标签名称
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.SwaggerTage'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取多个标签
      tags:
      - 标签
    post:
      description: 添加标签接口
      parameters:
      - description: 创建标签
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/params.CreateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.Swagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 新增标签
      tags:
      - 标签
  /api/v1/tags/{id}:
    put:
      description: 更新标签接口
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: string
      - description: 更新标签
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/params.UpdateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/app.Swagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 更新标签
      tags:
      - 标签
swagger: "2.0"
